name: Build Windows Executable

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:Version=${{ github.event.inputs.version }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: LogSplitor-${{ github.event.inputs.version }}
        path: bin/Release/net8.0-windows/win-x64/publish/LogSplitor.exe